freebsd_instance:
  image_family: freebsd-11-3-snap

task:
  install_script: pkg install -y gmake go bash
  script: sudo ALLOW_UNSUPPORTED_SYSTEM=yes BATCH=yes make package
  binaries_artifacts:
    path: "work/pkg/*"
