freebsd_instance:
  image_family: freebsd-11-3-snap

task:
  install_script: |
    pkg install -y go gmake ca_root_nss portshaker poudriere bash sudo git
    sudo bash -c 'cat > /usr/local/etc/poudriere.conf <<EOF
    NO_ZFS=yes
    FREEBSD_HOST=ftp://ftp.freebsd.org
    RESOLV_CONF=/etc/resolv.conf
    BASEFS=/usr/local/poudriere
    USE_PORTLINT=no
    USE_TMPFS=yes
    DISTFILES_CACHE=/usr/ports/distfiles
    CHECK_CHANGED_OPTIONS=yes
    EOF'
    sudo poudriere ports -c -F -f none -M /usr/local/poudriere/ports/default -p default
    sudo bash -c '
    cat > /usr/local/etc/portshaker.conf <<"EOF"
    # vim:set syntax=sh:
    #---[ Base directory for mirrored Ports Trees ]---
    mirror_base_dir="/var/cache/portshaker"
    #---[ Directories where to merge ports ]---
    ports_trees="default"
    use_zfs="no"
    poudriere_ports_mountpoint="/usr/local/poudriere/ports"
    default_poudriere_tree="default"
    default_merge_from="freebsd beat7"
    EOF'
    sudo bash -c 'cat > /usr/local/etc/portshaker.d/beat7 <<"EOF"
    #!/bin/sh
    shift
    . /usr/local/share/portshaker/portshaker.subr
    method="git"
    git_clone_uri="https://github.com/kalw/beats-fbsd-port.git"
    git_branch="master"
    run_portshaker_command $*
    EOF'
    sudo chmod +x /usr/local/etc/portshaker.d/{beat7,freebsd}
    sudo portshaker -U
    sudo portshaker -M
  script: |
    poudriere jail -c -j 112amd64 -v 11.2-RELEASE -a amd64
    poudriere bulk -j 112amd64 -p default sysutils/beats7
  binaries_artifacts:
    path: "/usr/local/poudriere/data/packages/112amd64-default/All/*"
