freebsd_instance:
  image_family: freebsd-11-3-snap

task:
  install_script: pkg install -y gmake go
  script: sudo ALLOW_UNSUPPORTED_SYSTEM=yes BATCH=yes make -j $(sysctl -n hw.ncpu) -C sysutils/beat7/ package
  binaries_artifacts:
    path: "sysutils/beat7/work/pkg/*"
