release_script_template: &RELEASE_SCRIPT_TEMPLATE
  environment:
    GITHUB_TOKEN: ENCRYPTED[f405516960bcf692dc7d4d3f46df621cfb1a0f2aec27c453bc83d839ff11192f9d79e35ca4e516780a3c0ad752e3c8c5]
  script: |
    ./custom_ports_04_release_github.sh
freebsd_instance:
  image_family: freebsd-11-4
task:
  timeout_in: 120m
  install_script: |
    ./custom_ports_01_prepare.sh
  matrix:
    - name: 11.2-RELEASE
      build_script: |
        echo ${CIRRUS_TASK_NAME}
        ./custom_ports_03_build.sh
      binaries_artifacts:
        path: "artefacts/*/*"
    - name: 11.3-RELEASE
      build_script: |
        echo ${CIRRUS_TASK_NAME}
        ./custom_ports_03_build.sh
      binaries_artifacts:
        path: "artefacts/*/*"
      << : *RELEASE_SCRIPT_TEMPLATE
    - name: 12.1-RELEASE
      build_script: |
        echo ${CIRRUS_TASK_NAME}
        ./custom_ports_03_build.sh
      binaries_artifacts:
        path: "artefacts/*/*"
      << : *RELEASE_SCRIPT_TEMPLATE
  
