#!/usr/bin/env bash

set -a
CUSTOM_PORTS_PATH=${CUSTOM_PORTS_PATH} # sysutils/beats7
CIRRUS_TASK_NAME=${CIRRUS_TASK_NAME:-"12.1-RELEASE"} # in case nothing provided
CUSTOM_PORT_RELEASE_TARGET=${CUSTOM_PORT_RELEASE_TARGET:-"${CIRRUS_TASK_NAME}"} # 12.3-RELEASE
CUSTOM_PORT_ARCH_TARGET=${CUSTOM_PORT_ARCH_TARGET:-'amd64'} # i386|amd64
CUSTOM_PORT_RELEASE_TARGET_MINIFIED="$(echo ${CUSTOM_PORT_RELEASE_TARGET} | sed -e 's/[-_.]//g')${CUSTOM_PORT_ARCH_TARGET}" # 123RELEASEamd64
CUSTOM_PORT_WORKING_DIR=${CUSTOM_PORT_WORKING_DIR:-"${CIRRUS_WORKING_DIR}"}
CUSTOM_PORT_TMP_DIR=${CUSTOM_PORT_TMP_DIR:-"${CIRRUS_WORKING_DIR}"}
if [ "x${CUSTOM_PORT_WORKING_DIR}" == "x" ] ; then CUSTOM_PORT_WORKING_DIR="$(pwd)" ; fi
if [ "x${CUSTOM_PORTS_PATH}" == "x" ] ; then CUSTOM_PORTS_PATH="$(cd ${CUSTOM_PORT_WORKING_DIR} ; find . -type d -depth 2 |grep -v .git|sed -e 's/^\.\///')" ; fi 
if [ "x${CUSTOM_PORT_TMP_DIR}" == "x" ] ; then CUSTOM_PORT_TMP_DIR="$(mktemp -d)" ; fi 
set +a

echo CUSTOM_PORT_RELEASE_TARGET: ${CUSTOM_PORT_RELEASE_TARGET}
echo CUSTOM_PORT_ARCH_TARGET: ${CUSTOM_PORT_ARCH_TARGET}
echo CUSTOM_PORT_RELEASE_TARGET_MINIFIED: ${CUSTOM_PORT_RELEASE_TARGET_MINIFIED}
echo CUSTOM_PORT_WORKING_DIR: ${CUSTOM_PORT_WORKING_DIR}
echo CUSTOM_PORTS_PATH: ${CUSTOM_PORTS_PATH}
echo CUSTOM_PORT_TMP_DIR: ${CUSTOM_PORT_TMP_DIR}